# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

resources:
  repositories:
    - repository: templates
      type: github
      name: rivoric/yamlbuildtemplate
      endpoint: rivoric

pool:
  vmImage: vs2017-win2016
  
variables:
  buildConfiguration: 'Release'
  projectFile: simple.web.app/simple.web.app/simple.web.app.csproj

steps:

# build using a template
- template: templates/build-dotnetcore.yml@templates
  parameters:
    projectFile: $(projectFile)
    buildConfiguration: $(buildConfiguration)

# pubish drop (build artifact)
- task: PublishBuildArtifacts@1