# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'
  projectFile: simple.web.app/simple.web.app/simple.web.app.csproj

steps:

# dotnet core build
- script: |
    dotnet restore $(projectFile)
    dotnet build --configuration $(buildConfiguration) $(projectFile)
    dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx $(projectFile)
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY $(projectFile)

# publish test results
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

# pubish drop (build artifact)
- task: PublishBuildArtifacts@1